"""Measure accuracy of a model's *exported artifact* on a standard dataset.

    python tools/evaluate.py --model yolox_s --coco-root /data/coco
    python tools/evaluate.py --task object_detection --coco-root /data/coco

Object detection: COCO val2017 box AP (pycocotools), using exactly the ONNX
file and ``detector.py`` of the collection — so the number checks the export
and our pre/post-processing, not the upstream PyTorch model.

``--coco-root`` must contain ``val2017/`` and
``annotations/instances_val2017.json`` (download:
http://images.cocodataset.org/zips/val2017.zip and
http://images.cocodataset.org/annotations/annotations_trainval2017.zip).

Evaluation settings (recorded in the result): score threshold 0.001, at most
100 detections per image (COCO maxDets), NMS IoU 0.65 for models that run NMS
in ``detector.py``; each model's own input size and resize policy.

Results go to ``<task>/<model>/accuracy.yaml`` (generated, one record per
dataset/runtime/precision).
"""

from __future__ import annotations

import argparse
import datetime as dt
import inspect
import json
import subprocess
import sys
import time
from pathlib import Path

import cv2
import numpy as np
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from tools.mlmc.catalog import Model, all_models, get_model  # noqa: E402
from tools.mlmc.detection import COCO80, COCO91_IDS, PROVIDERS, provider_precision  # noqa: E402

NAME_TO_CAT = dict(zip(COCO80, COCO91_IDS))
SCORE_THR = 0.001
MAX_DETS = 100
NMS_IOU = 0.65


def eval_coco_detection(model: Model, coco_root: Path, provider: str,
                        limit: int | None) -> dict:
    from pycocotools.coco import COCO
    from pycocotools.cocoeval import COCOeval

    gt = COCO(str(coco_root / "annotations" / "instances_val2017.json"))
    img_ids = sorted(gt.getImgIds())[:limit] if limit else sorted(gt.getImgIds())

    kwargs = {"provider": provider}
    params = inspect.signature(_runner_cls(model)).parameters
    if "score_thr" in params:
        kwargs["score_thr"] = SCORE_THR
    if "iou_thr" in params:
        kwargs["iou_thr"] = NMS_IOU
    det = model.load_runner(**kwargs)

    results, t0 = [], time.perf_counter()
    for k, img_id in enumerate(img_ids):
        info = gt.loadImgs(img_id)[0]
        img = cv2.imread(str(coco_root / "val2017" / info["file_name"]))
        d = det(img)
        order = np.argsort(-d.scores)[:MAX_DETS]
        for i in order:
            x1, y1, x2, y2 = (float(v) for v in d.boxes[i])
            results.append({"image_id": img_id, "category_id": NAME_TO_CAT[d.labels[i]],
                            "bbox": [round(x1, 2), round(y1, 2),
                                     round(x2 - x1, 2), round(y2 - y1, 2)],
                            "score": round(float(d.scores[i]), 5)})
        if (k + 1) % 1000 == 0:
            print(f"  {k + 1}/{len(img_ids)} images", flush=True)
    elapsed = time.perf_counter() - t0

    if not results:
        raise SystemExit("no detections")
    ev = COCOeval(gt, gt.loadRes(results), "bbox")
    ev.params.imgIds = img_ids
    ev.evaluate(); ev.accumulate(); ev.summarize()
    s = ev.stats
    names = ["AP", "AP50", "AP75", "AP_small", "AP_medium", "AP_large"]
    return {
        "dataset": "COCO val2017" + (f" (first {limit} images)" if limit else ""),
        "images": len(img_ids),
        "metrics": {n: round(float(v) * 100, 1) for n, v in zip(names, s[:6])},
        "settings": {"score_threshold": SCORE_THR, "max_dets": MAX_DETS,
                     "nms_iou": NMS_IOU if "iou_thr" in params else None,
                     "evaluator": "pycocotools COCOeval (bbox)"},
        "wall_time_s": round(elapsed, 1),
    }


def _runner_cls(model: Model):
    import importlib.util
    from tools.mlmc.catalog import RUNNERS
    filename, cls = RUNNERS[model.task]
    spec = importlib.util.spec_from_file_location(f"_probe_{model.name}", model.dir / filename)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return getattr(mod, cls)


def ort_version() -> str:
    import importlib.metadata as md
    for name in ("onnxruntime-gpu", "onnxruntime"):
        try:
            return f"{name} {md.version(name)}"
        except md.PackageNotFoundError:
            pass
    return "unknown"


def save(model: Model, rec: dict):
    path = model.dir / "accuracy.yaml"
    records = yaml.safe_load(path.read_text(encoding="utf-8")) if path.exists() else []
    records = [r for r in (records or []) if r.get("id") != rec["id"]] + [rec]
    records.sort(key=lambda r: r["id"])
    path.write_text("# GENERATED by tools/evaluate.py — do not edit by hand.\n"
                    + yaml.safe_dump(records, sort_keys=False, allow_unicode=True),
                    encoding="utf-8", newline="\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--model")
    ap.add_argument("--task", default="object_detection")
    ap.add_argument("--coco-root", type=Path, required=True)
    ap.add_argument("--provider", default="cuda", choices=list(PROVIDERS))
    ap.add_argument("--limit", type=int, help="evaluate only the first N images (smoke test)")
    args = ap.parse_args()

    if not args.model:
        for m in all_models(args.task):
            if m.artifact_path("onnx").exists():
                print(f"== {m.name}", flush=True)
                subprocess.run([sys.executable, __file__, "--model", m.name,
                                "--coco-root", str(args.coco_root), "--provider", args.provider]
                               + (["--limit", str(args.limit)] if args.limit else []))
        return

    model = get_model(args.model)
    if model.task != "object_detection":
        raise SystemExit(f"no evaluator for task {model.task!r} yet")
    res = eval_coco_detection(model, args.coco_root, args.provider, args.limit)
    prov_file = model.weights_dir / "provenance.json"
    sha = json.loads(prov_file.read_text()).get("sha256") if prov_file.exists() else None
    runtime = "onnxruntime-" + args.provider.split("-")[0]
    precision = provider_precision(args.provider)
    rec = {
        "id": f"coco-val2017{'-limit' + str(args.limit) if args.limit else ''}_{runtime}_{precision}",
        "date": dt.date.today().isoformat(),
        **res,
        "runtime": runtime,
        "runtime_version": ort_version(),
        "precision": precision,
        "artifact": {"file": model.meta["artifacts"]["onnx"]["file"], "sha256": sha},
    }
    print(yaml.safe_dump(rec, sort_keys=False))
    if not args.limit:
        save(model, rec)


if __name__ == "__main__":
    main()
